### ISSUE TITLE
jq: error (at <stdin>:4 [and 1]): Cannot iterate over null (null)

### ISSUE THREAD

**Issue by telix5000** [RandomNinjaAtk/docker-lidarr-extended#10]
I am getting a lot of these in the logs. It seems to be grabbing files, but then nothing happens with them. 

For example:

/downloads/lidarr-extended/complete/Dabeull-Cosmic Fonk (2022)-FLAC-DEEZER (4 items)
Tagging:
    Dabeull - Cosmic Fonk
URL:
    https://musicbrainz.org/release/5071e015-410f-4685-8e2c-052c8373ea8d
(Similarity: [32;01m100.0%[39;49;00m) [37m(Digital Media, 2022, FR, Dabeull Records)[39;49;00m
 * Cosmic Fonk ([37mI[39;49;00mntro) -> Cosmic Fonk [31;01m- [39;49;00m([37mi[39;49;00mntro)
2022-07-06 12:45:17 :: 1 of 283593 :: Dabeull :: Cosmic Fonk :: SUCCESS: Matched with beets!
2022-07-06 12:45:17 :: 1 of 283593 :: Dabeull :: Cosmic Fonk :: BEETS MATCH FOUND!
2022-07-06 12:53:44 :: 1 of 283593 :: Dabeull :: Cosmic Fonk :: ERROR :: Already Imported Album (Missing)
2022-07-06 12:53:44 :: 1 of 283593 :: Dabeull :: Cosmic Fonk :: ERROR :: Previously Found, skipping...
2022-07-06 12:53:44 :: 1 of 283593 :: Dabeull :: Cosmic Fonk :: Already Imported, skipping...
jq: error (at <stdin>:4): Cannot iterate over null (null)
jq: error (at <stdin>:4): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)

**Comment by RandomNinjaAtk** [comment]
Update to the latest version and see if that clears things up

**Comment by telix5000** [comment]
OK -- it may take about a day to sync it back up unless this thing checkpoints where it left off.

**Comment by RandomNinjaAtk** [comment]
I just noticed how big your list is, give me a few hours and I'll see if I can push an update to help speed that up... 

I'll post an update when I have it ready...

**Comment by telix5000** [comment]
Awesome! That would help like you wouldn't imagine!

**Comment by RandomNinjaAtk** [comment]
Just realized there was a bug, wait 10-15 minutes before updating, you need to be on v1.0.85

**Comment by telix5000** [comment]
It seems to be pulling the 10,000 at a time -- now I am waiting for it to finish up and see if this bug reappears. Give me an hour or so.

**Comment by telix5000** [comment]
OK, looks good so far. It imported in an album and no weird errors showed up. Thank you so much!
