### ISSUE TITLE
Music Videos

### ISSUE THREAD

**Issue by telix5000** [RandomNinjaAtk/docker-lidarr-extended#11]
I defined the music videos directory via Docker compose, however, the music videos are still being dropped into the same directory as the music. Is the music-videos value even of any use if it's just being ignored?

**Comment by telix5000** [comment]
Also, I think the videos from Tidal need to have the name-video.xyz format, otherwise they come up as Extras. As far as I recall, they need to have the -video at the end of the name in order to indicate they are a music video; there was some guide:

    -behindthescenes (behind the scenes)
    -concert (concert performance)
    -interview (artist interview)
    -live (live music video)
    -lyrics (lyrics music video
    -video (regular music video)

Not sure if that's asking too much, but it seems to be the more optimal way of adding them in.

**Comment by RandomNinjaAtk** [comment]
Plex prefers them in the album folder, if you don't want them there, don't use the music video script, you can disable it in lidarr under Custom scripts. There is more to be done with videos...
