### ISSUE TITLE
[Bug]: logs show attempts to use tidal when only deezer is in the compose file

### ISSUE THREAD

**Issue by BackedUpBooty** [RandomNinjaAtk/docker-lidarr-extended#119]
**Describe the bug**
Although Tidal is not selected for use in the compose file, LidExt still seems to be trying to access Tidal for Extended Video.

**To Reproduce**
1. set `dlClientSource=deezer` and remove `tidalCountryCode` in docker-compose.yml
2. include `arlToken` for deezer

**Expected behavior**
Only deezer is used instead of tidal

**Log Data**
https://gist.github.com/BackedUpBooty/b6937cd07b37d164479e690efbd9f09b (logs)
https://gist.github.com/BackedUpBooty/c058bc2fda63fe8ee2525cba9d31eb4a (environment in compose file)

**Docker Info:**
 - Docker Version: 22.10.3
 - Extended Script Version: latest image (pulled 30 mins ago)

**Additional context**
Not sure if relevant - I've added Muse and Silverchair to this Lidarr instance to test, and various videos have been downlodaed fine and viewable in Plex.

**Comment by RandomNinjaAtk** [comment]
Ah, I don't think the video script follows that setting at all, so this is probably a real bug. I'll look at correcting it as soon as I'm able too. I only recall the audio script having the correct logic to handle it.

**Comment by BackedUpBooty** [comment]
Got it. Yeah the Extended Audio is definitely only bringing up deezer. Great tool you've got here, thanks for taking the time.

**Comment by RandomNinjaAtk** [comment]
I think its fixed with the minor change, seems like I had partially accounted for the setting, just missed a spot for it... You'll have to update to the latest and see if its resolved.

**Comment by BackedUpBooty** [comment]
confirmed, thanks, no tidal now!

i seem to be getting some errors with deezer though (which existed before) where deezer can't add top 10 artists to lidarr (seems to be an addArtist API issue, with `"errorMessage": "\u00271\u0027 is invalid after a value. Expected either \u0027,\u0027, \u0027}\u0027, or \u0027]\u0027. Path: $ | LineNumber: 4 | BytePositionInLine: 0."`) 

Should I raise a new issue?

**Comment by RandomNinjaAtk** [comment]
Separate issues are better for tacking purposes.
