### ISSUE TITLE
jq Performance

### ISSUE THREAD

**Issue by telix5000** [RandomNinjaAtk/docker-lidarr-extended#12]
I have been running this overnight, but it seems to be stuck on this jq -r command for over an hour. I'm not a jq expert, but is it going to take over an hour for each entry to import? I don't see any I/O via htop happening, just pegging the processor.

**Comment by RandomNinjaAtk** [comment]
Are you on the latest version?

**Comment by telix5000** [comment]
Yes. I updated to what you pushed. It’s this jq process just taking a very long time to run. I have read about this happening before. Read something about using a stream instead or another program entirely; but this is out of my wheelhouse.

**Comment by RandomNinjaAtk** [comment]
Well without any logs or more detail, nothing further can be done to investigate. Feel free to open a new issue if you have some data that can be reviewed... Also make sure you have the latest update, everything is updated/improved frequently

**Comment by telix5000** [comment]
Sure, which log does the jq process log to? There's quite a few in the log directory.
