### ISSUE TITLE
[Bug]: cannot auto add artists from deezer lists and deezer extended audio download fails

### ISSUE THREAD

**Issue by BackedUpBooty** [RandomNinjaAtk/docker-lidarr-extended#120]
**Describe the bug**
No 'Top 10' artists from deezer (the only list enabled) can be auto-added, and Extended Audio Download fails.

**To Reproduce**
1. Docker-compose.yml has the following env variables: 
```
- arlToken=$ARLTOKEN
- audioLyricType=both
- dlClientSource=deezer
- addDeezerTopArtists=true
- addDeezerTopAlbumArtists=false
- addDeezerTopTrackArtists=false
- topLimit=10
- addRelatedArtists=false
```
2. Spin up container
3. Watch logs until error happens (on all 10 artists)
4. Continue to watch logs until `Extended Audio` error occurs
5. Try updating the arl token as suggested, no change to Extended Audio

**Expected behavior**
Top 10 artists from Deezer are added to lidarr, and Extended Audio doesn't error out

**Log Data**
https://gist.github.com/BackedUpBooty/8c683c06bd05f47dacd90262d22242c0 (deezer top 10 artist add error)
https://gist.github.com/BackedUpBooty/3eb20e66cb2a9aa2d739bdc098b7dfaf (Extended Audio Download failure)

**Docker Info:**
 - Docker Version: 22.10.3
 - Extended Script Version: latest image

**Additional context**
I have a free US deezer account, but I am not currently in the US, so my lidarr-extended container network is going through another VPN container. I've confirmed however that the IP of that container is in the US:
```
root@6ae324623d75:/config# curl ipinfo.io/json
{
  "ip": "xx.xx.xxx.xx", [redacted]
  "city": "San Jose",
  "region": "California",
  "country": "US",
  "loc": "37.3394,-121.8950",
  "org": "AS35913 DediPath",
  "postal": "95103",
  "timezone": "America/Los_Angeles",
  "readme": "https://ipinfo.io/missingauth"
```

**Comment by RandomNinjaAtk** [comment]
Not able to replicate this issue:
```
2022-11-07 11:42:56 :: Extended Audio :: 1.0.271 :: Finding Top Artists...
2022-11-07 11:42:56 :: Extended Audio :: 1.0.271 :: 1 Top Artists Found...
2022-11-07 11:42:57 :: Extended Audio :: 1.0.271 :: 1 of 1 :: Kanye West :: Searching Musicbrainz for Deezer artist id (230)
2022-11-07 11:43:02 :: Extended Audio :: 1.0.271 :: 1 of 1 :: Kanye West :: Adding Kanye West to Lidarr (164f0d73-1234-4e2c-8743-d77bf2191051)...
2022-11-07 11:43:02 :: Extended Audio :: 1.0.271 :: STATUS :: LIDARR BUSY :: Pausing/waiting for all active Lidarr tasks to end...
2022-11-07 11:44:05 :: Extended Audio :: 1.0.271 :: FINDING MISSING ALBUMS :: sorted by date
```
No errors and working as expected in my system/configuration.

**Comment by BackedUpBooty** [comment]
Not sure why this is an invalid report. The error is clearly there in the lidarr API on my system. Does Deezer need to be a paid account?

**Comment by RandomNinjaAtk** [comment]
As you can see from my testing it works and if I can’t reproduce it, there is no hope for me to help fix it. It honestly doesn’t require an account at all to work, accounts are only required for download execution.

So if your experiencing the issue, it’s likely something unique to your particular setup/configuration.

**Comment by RandomNinjaAtk** [comment]
So I ran into a similar bug, but was my own doing with recent changes.

After reading yours more, what is the configured root folders in your lidarr setup? Are you using more than one? What are the full paths?

It looks like its barfing due to your root folder/path configuration.

**Comment by BackedUpBooty** [comment]
Hey thanks for circling back to this. 

My docker-compose volumes are mapped like this which essentially matches my Sonarr/Radarr setups:
```
volumes:
      - ./lidarr:/config
      - $MEDIADIR:/downloads-lidarr-extended
      - $MEDIADIR:/media
      - $MEDIADIR/media/music videos:/music-videos
```
`MEDIADIR`=`/volume1/docker/libraries`. The lidarr config is in `/volume1/docker/compose/media/lidarr` where the `docker-compose.yml` is in `/volume1/docker/compose/media`.

There are no folder mappings required in the lidarr gui to make sure downloads are found and can be renamed/moved etc.

**Comment by RandomNinjaAtk** [comment]
No what I'm asking about is under Lidarr Web UI: Settings -> Media management -> Root Folders

If you have more than one root folder, that could likely be the issue...

**Comment by BackedUpBooty** [comment]
Ah gotcha. Yes I have a root folder for music and one for music videos. Is the music videos one not required?

**Comment by RandomNinjaAtk** [comment]
You shouldn't be mapping the root folder for videos in Lidarr Web UI, Lidarr can do nothing with them, so it has no purpose. You should remove that and see if it works.

**Comment by BackedUpBooty** [comment]
Looks like that got it, thanks for the help.
