### ISSUE TITLE
[Bug]: Reauthorization to Tidal seems to be acting up

### ISSUE THREAD

**Issue by Repooc** [RandomNinjaAtk/docker-lidarr-extended#125]
**Describe the bug**
Seems that login isnt working for Tidal now or something else is going on...

**To Reproduce**
1. Start the container
2. See url to authorize Tidal
3. Authorize Tidal
4. it appears to search then seems to have to repeat authorization and something fails, im not sure
... sometimes it appears to start "searching" but ends up wanting me to reauthorize again

**Expected behavior**
Authorize tidal, it works for the week before having to do it again

**Log Data**
![image](https://user-images.githubusercontent.com/1479745/201509017-e56c704d-a25a-4810-957b-04112e8e4c34.png)

**Docker Info:**
 - Docker Version: 20.10.18 (running on an unraid server)
 - Extended Script Version: running `randomninjaatk/lidarr-extended` which i assume pulls the latest version

**Additional context**
On a side note, I swore I was in a discord server of yours for all your projects, not sure if I left or if you closed it but I can't seem to find any invite link for one now if there is one... Please share a link if you still have one and accepting people in to it.

**Comment by Repooc** [comment]
Just a thought, maybe Tidal is throttling my account or something...

**Comment by RandomUser345** [comment]
Havin same issues: but what works for me is following: connect to the bash in the container, execute tidal-dl there, switch api key to 1 (master only), authorize with link, switch back to the original api key to 4 (normal/hifi/master), authorize with link. Then it usually works for the 7 days the token is valid.

**Comment by RandomNinjaAtk** [comment]
I'm not personally seeing any issue. But maybe something changed

**Comment by RandomUser345** [comment]
Had this issue from the start... but I figured I'm the only one. Maybe its a ARM64 problem: thats why it's not very common?

**Comment by RandomNinjaAtk** [comment]
Maybe the client doesn't support arm? Idk.

**Comment by RandomNinjaAtk** [comment]
It's possible that 1.0.295 may resolve this, but you'd have to test to know if it helped....

**Comment by Repooc** [comment]
I am not experiencing the issue at the current moment but i have not been looking into it the past couple days but could have been from ur fix.  Thank you for looking into it though.
