### ISSUE TITLE
[Bug]: Lidarr-extended creates two album folders for one album

### ISSUE THREAD

**Issue by steve1977** [RandomNinjaAtk/docker-lidarr-extended#133]
Downloading albums with script using tidal. Please see below what is being created (two album folders although only one album downloaded):

/Seconds of Summer/5 Seconds of Summer - Single - 2022 - Me Myself and I/0101 - Me Myself and I.flac
/Seconds of Summer/5 Seconds of Summer - Single - 2022 - Me Myself and I/album.nfo
/Seconds of Summer/5 Seconds of Summer - Single - 2022 - Me Myself and I/folder.jpg
/Seconds of Summer/5 Seconds of Summer - Single - 2022 - Me Myself & I/album.nfo
/Seconds of Summer/5 Seconds of Summer - Single - 2022 - Me Myself & I/folder.jpg

It may be because of an upgrade of quality and not deleting the folder of the album that was upgraded in quality?

**Comment by RandomNinjaAtk** [comment]
This is a lidarr issue, not a script issue. Lidarr handles all final naming and data storage....
