### ISSUE TITLE
[Feat]: Download videos for tagged artists only

### ISSUE THREAD

**Issue by bmatheny** [RandomNinjaAtk/docker-lidarr-extended#141]
**Is your feature request related to a problem? Please describe.**

If you have a “large” lidarr library, the video download functionality is essentially unusable as is unless you have massive amounts of storage. There’s no way to restrict what videos are downloaded, so you just disable video downloads.

**Describe the solution you'd like**

Ideally I could do something like specify a lidarr tag, and only artists with that tag get video downloads. The tag API for lidarr makes this possible. For example:

* -e videoDownloadTag=“favorites” only downloads videos for artists tagged “favorites”
* -e videoDownloadTag=“” (compatibility case) behaves as it does today
* -e videoDownloadTag=“no-such-tag” behaves either as today (all artists are considered) or (my preference) as a tag that has no artists yet associated with it

**Describe alternatives you've considered**

There are likely methods besides using tags, eg profiles. But tags feels like the right way to do this.

**other**

I looked at the video script. I’d be happy to put up a PR if this is something you think makes sense, and you don’t have time.

**Comment by RandomNinjaAtk** [comment]
PR welcome

**Comment by bmatheny** [comment]
PR up at #142

**Comment by bmatheny** [comment]
Merged
