### ISSUE TITLE
Lidarr search issues

### ISSUE THREAD

**Issue by Yosh82** [RandomNinjaAtk/docker-lidarr-extended#145]
**Describe the bug**
Unable to add to Lidarr using musicbrainz ID (issue for a while now) - 

Unable to find some new musicbrainz additions using the Album name (which was previously working, although had a long delay between adding to MB and Lidarr finding it) - This last worked around a two weeks ago and has since stopped.

Note: This seems to be for newly added MB releases - It still finds most releases which were added over 2 weeks ago. I can provide more examples if needed. I've also tested in an incognito tab to rule out my local cache.

**To Reproduce**
Steps to reproduce the behaviour:

example: "lidarr:c62a0504-ab59-46fd-a9c6-35db42a528a1" should find release "https://musicbrainz.org/release/c62a0504-ab59-46fd-a9c6-35db42a528a1" but shows zero results,

Previously, I added by the Album name instead; Now unable to search using the name of the album "Strictly the Best 25" (and 29 too).  This was working until around 2 weeks ago, although did take a very long time for new additions on musicbrainz to show in Lidarr.

**Expected behavior**
To find the releases with both the MB ID and the Album name

**Log Data**
No errors outputted

**Docker Info:**
 - Docker Version: Unraid (will update if needed)
 - Extended Script Version Latest

**Additional context**

**Comment by RandomNinjaAtk** [comment]
This is not a bug and not related to this docker at all, what your asking about is in-regards to Lidarr itself, so your issue would be better to be posted there.

However, on that note, your not using the correct ID, you have to use the release group ID (https://musicbrainz.org/release-group/628d2591-5320-497e-9c53-5914b1cfbd56), example: lidarr:628d2591-5320-497e-9c53-5914b1cfbd56

**Comment by Yosh82** [comment]
> ID, you have

Thanks for the response.
