### ISSUE TITLE
/scripts Audio.sh stops constantly when ran from container bash console

### ISSUE THREAD

**Issue by neilanthonystuckey** [RandomNinjaAtk/docker-lidarr-extended#147]
Is there a preferred way to run the Audio.sh script ? i tend to get a couple downloads and then it asks for arl over and over. I tried to enter the arl in the the script itself with # and without # commenting it out with the same results.

i am running ubuntu 22.04 using lidarr extended in docker.

Lidarr
Version
1.1.0.2649
Package Version
1.1.0.2649-ls62 by [linuxserver.io](https://www.linuxserver.io/)
.NET
Yes (6.0.7)
DB Migration
58
AppData directory
/config
Startup directory
/app/lidarr/bin

**Comment by RandomNinjaAtk** [comment]
The ARL key is entered as part of the container/docker parameters, see here: https://github.com/RandomNinjaAtk/docker-lidarr-extended#parameters

Then when you execute manually, no input should be required by the user

**Comment by neilanthonystuckey** [comment]
You pointed me in the direction i needed.  When i setup the container i copied the arl token from browser web tools.  I accidentally copied extra info into the arl environment variable for lidarr-extended.  Re-created the container with correct info it seems to be working great now. Thanks for the fast response and awesome scripts and software.

This can be closed
