### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by swedishstyle** [RandomNinjaAtk/docker-lidarr-extended#15]
**Describe the bug**
"Folder is not writable by user abc"

**To Reproduce**
N/A

**Expected behavior**
The user is able to write to the music directory, as it is mapped to the correct user in Docker

**Docker Info:**
 - Docker Version: 20.10.17

**Additional context**
I migrated my Lidarr database from Windows full install to a Linux docker install. I've had no issues with it seeing all of my existing music, as well as downloading watched files, but I cannot add the root folder, due to the error above. I have the PGID and PUID mapped to a user with owner privileges on the folder.

**Comment by RandomNinjaAtk** [comment]
The base image is linuxserver lidarr container. So setting this up is the same as that. You could look for support there. In windows, you probably need to make sure the permissions are wide open for the folder you mapped. So the equivalent of 777 on Linux, so I wold suggest looking at your file permissions from windows and trying to relax them as much as possible.
