### ISSUE TITLE
No Plex Music Type libraries found

### ISSUE THREAD

**Issue by PutzJimmy** [RandomNinjaAtk/docker-lidarr-extended#161]
Hi. Trying to get the PlexNotify.bash working but stuck on:

2022-12-14 12:16:03 :: PlexNotify :: 1.0.6 :: Plex Connection Established, version:
2022-12-14 12:16:09 :: PlexNotify :: 1.0.6 :: ERROR: No Plex Music Type libraries found
2022-12-14 12:16:09 :: PlexNotify :: 1.0.6 :: ERROR: Exiting...

**Comment by RandomNinjaAtk** [comment]
Seems like you have a user configuration error somewhere. For it to work, you must have a library in Plex that is the music type and also have the same root folder that is configured in lidarr, configured in the plex music library.

**Comment by PutzJimmy** [comment]
I have a music library called Music and it shares the same mount as the other dockers /Media
Does it need to be in the music folder as in /Media/Music?

**Comment by RandomNinjaAtk** [comment]
Does the script provide you a Plex Version number? Or is it blank, like in the log output your showing?

If the version number isn't showing, try updating your token...

Honestly, here is the code that looks for it:
https://github.com/RandomNinjaAtk/docker-lidarr-extended/blob/bdf8f5b04ccb00e4000e453b963388b27b1f81e3/root/scripts/PlexNotify.bash#L42-L53

Because everyone's plex configuration is different, it may just be something unique to your setup and I won't likely be able to replicate to troubleshoot it further.

**Comment by PutzJimmy** [comment]
Nope it just repeats what i pasted above over and over, no version number. Config has the correct adress and token verified working in other programs. Triggering a test from inside Lidarr gives 2022-12-14 12:49:30 :: PlexNotify :: 1.0.6 :: Tested Successfully

**Comment by RandomNinjaAtk** [comment]
Triggering a test won't do anything based on how Lidarr is designed. But it sounds like its not connecting. So make sure you have no extra whitespace before and after the URL and token. Also the url should not contain a trailing "/", so make sure its like: `http://x.x.x.x:32400`.

**Comment by PutzJimmy** [comment]
They are correctly filled in checked like 50 times already lol. Adress works in firefox+chrome. Prowlarr and tautilli works fine connecting with same info

**Comment by RandomNinjaAtk** [comment]
Idk, nothing more I can do without having the XML data from your specific config to troubleshoot.

`curl -s "$plexUrl/library/sections?X-Plex-Token=$plexToken"`
Replace the variables `$plexUrl` and `$plexToken` with your information and post the output.

**Comment by PutzJimmy** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="5" allowSync="0" title1="Plex Library">
<Directory allowSync="1" art="/:/resources/movie-fanart.jpg" composite="/library/sections/1/composite/1671018536" filters="1" refreshing="0" thumb="/:/resources/movie.png" key="1" type="movie" title="Movie" agent="tv.plex.agents.movie" scanner="Plex Movie" language="en-US" uuid="ba086e38-0140-43d3-917d-65078c40450b" updatedAt="1671018591" createdAt="1662272329" scannedAt="1671018536" content="1" directory="1" contentChangedAt="4659017" hidden="0">
<Location id="15" path="/Media/Movie" />
</Directory>
<Directory allowSync="1" art="/:/resources/movie-fanart.jpg" composite="/library/sections/9/composite/1671005371" filters="1" refreshing="0" thumb="/:/resources/movie.png" key="9" type="movie" title="Movie 2160p" agent="tv.plex.agents.movie" scanner="Plex Movie" language="en-US" uuid="d7626ba6-d85f-4002-b744-af343bc4a9d5" updatedAt="1671005419" createdAt="1662575289" scannedAt="1671005371" content="1" directory="1" contentChangedAt="4552481" hidden="0">
<Location id="21" path="/Media/Movie 2160p" />
</Directory>
<Directory allowSync="1" art="/:/resources/show-fanart.jpg" composite="/library/sections/7/composite/1671017962" filters="1" refreshing="0" thumb="/:/resources/show.png" key="7" type="show" title="Tv" agent="tv.plex.agents.series" scanner="Plex TV Series" language="en-US" uuid="b983c549-8708-44c9-b894-b048ddc2dd31" updatedAt="1671018024" createdAt="1662280630" scannedAt="1671017962" content="1" directory="1" contentChangedAt="4658529" hidden="0">
<Location id="12" path="/Media/Tv" />
</Directory>
<Directory allowSync="1" art="/:/resources/show-fanart.jpg" composite="/library/sections/10/composite/1671007891" filters="1" refreshing="0" thumb="/:/resources/show.png" key="10" type="show" title="Tv 2160p" agent="tv.plex.agents.series" scanner="Plex TV Series" language="en-US" uuid="fe93d018-98ff-46ce-b8de-106ef2c3f74a" updatedAt="1671007949" createdAt="1662575348" scannedAt="1671007891" content="1" directory="1" contentChangedAt="4427496" hidden="0">
<Location id="22" path="/Media/Tv 2160p" />
</Directory>
<Directory allowSync="1" art="/:/resources/artist-fanart.jpg" composite="/library/sections/5/composite/1671006358" filters="1" refreshing="0" thumb="/:/resources/artist.png" key="5" type="artist" title="Music" agent="tv.plex.agents.music" scanner="Plex Music" language="en" uuid="9eeaa648-d23d-4c42-95b4-9e07c44359f0" updatedAt="1671006416" createdAt="1662279820" scannedAt="1671006358" content="1" directory="1" contentChangedAt="4650022" hidden="0">
<Location id="17" path="/Media/Music" />
</Directory>
</MediaContainer>

**Comment by RandomNinjaAtk** [comment]
Based on the existing code and the file you provided, found no errors with the code. So my only guess is still an issue with the connection that is not detected... 

I have just pushed a change based on some testing to better detect an error with connecting. I believe this all boils down to a connection issue... So my suggestion would be to update after the new image is out in the next 20 or so minutes and see if you get an error message about the connection. If you do, I'd suggest reviewing your docker parameters for whitespace issue, trying a new token... 

You'll also see what it shows is the token/url so you can check it more easily for whitespace or typo error...

**Comment by PutzJimmy** [comment]
Found the error now, for some reason the dockers from you ended up in a different docker network that was not in the firewall allow on the server hosting plex... Thx for the help =)
2022-12-15 01:47:41 :: PlexNotify :: 1.0.7 :: Plex Connection Established, version: 1.30.1.6483-85af1e381
2022-12-15 01:47:58 :: PlexNotify :: 1.0.7 :: Plex Scan notification sent! (5 :: /Media/Music/Iggy Pop)

**Comment by RandomNinjaAtk** [comment]
@PutzJimmy Glad you figured it out, I did improve the connection validation test, so it should have at least reported a connection error to help find the problem in the future for other users because it did not account for some edge case scenarios that are now accounted for...
