### ISSUE TITLE
'notfound' directory does not exist in /config/extended

### ISSUE THREAD

**Issue by captainnapalm** [RandomNinjaAtk/docker-lidarr-extended#162]
Not sure what level of issue this is, or maybe it's a logging message error, but the directory for 'notfound' doesn't exist in the location specified by the log output.

`09:25:35 :: Audio :: 1.0.305 :: 1 :: missing :: Filtering Album IDs by removing previously searched Album IDs (/config/extended/notfound/<files>)`

My directory for /config/extended only contains the following

```
brendan@prometheus:/mnt/nvmetank/appdata/lidarr-extended/extended$ ls -al
total 91
drwxrwxrwx 5 99 users     6 Dec 13 22:42 .
drwxr-xr-x 9 99 users    15 Dec 14 09:28 ..
-rw-r--r-- 1 99 users 45056 Dec 13 22:42 beets-library.blb
drwxrwxrwx 7 99 users     7 Dec 13 22:41 cache
drwxrwxrwx 5 99 users     7 Dec 13 22:41 logs
drwxrwxrwx 2 99 users    17 Dec 14 03:01 scripts
``` 

Is this just a typo in the error message? Should I have a 'notfound' directory here as indicated, or should it be /config/extended/logs/notfound/<files>?

I also have the following output in my logs that I'm not sure what to do about:

`ls: cannot access '/config/extended/cache/lidarr/list/*-cutoff': No such file or directory`

**Comment by RandomNinjaAtk** [comment]
Would be a typo, it exists, its located at: `/config/extended/logs/notfound`

**Comment by RandomNinjaAtk** [comment]
`ls: cannot access '/config/extended/cache/lidarr/list/*-cutoff': No such file or directory`

You should be able to ignore this error most likely....

Also after the latest image is built, it will show the correct location going forward for notfound folder.

**Comment by captainnapalm** [comment]
To force lidarr and the audio scripts to recheck outside of the notfound setting, I can delete the files in the notfound directory, correct?

**Comment by RandomNinjaAtk** [comment]
> To force lidarr and the audio scripts to recheck outside of the notfound setting, I can delete the files in the notfound directory, correct?

Yarp

**Comment by RandomNinjaAtk** [comment]
I'm thinking your request/issue should now be resolved. If not please feel free to comment/re-open.
