### ISSUE TITLE
[Feat]: Readarr-Extended

### ISSUE THREAD

**Issue by dvdgorila** [RandomNinjaAtk/docker-lidarr-extended#163]
Sorry for hijacking the lidarr repo. Your Extended Arr version are awesome... 

I was wondering if you had any plans to release an extended version of Readarr.. specifically for audiobooks. 

These links should provide some ideas for laying the ground work for an extended version that would fit nicely with Plex. 

https://github.com/seanap/Plex-Audiobook-Guide
https://github.com/seanap/auto-m4b
https://github.com/Neurrone/beets-audible

**Comment by RandomNinjaAtk** [comment]
I could see something like https://github.com/seanap/auto-m4b and https://github.com/Neurrone/beets-audible would be more applicable for sabnzbd-extended.

As for a readarr-extended, some of the auto-config, queue cleaner type things would probably be applicable to it and could be easily accomplished.

**Comment by dvdgorila** [comment]
I'll look into the post download utilities since I don't only use nzb as source.  As far auto-config and queue cleaner, etc, do you plan on doing a readarr build?

**Comment by RandomNinjaAtk** [comment]
I would probably start with [sabnzbd-extended](https://github.com/RandomNinjaAtk/docker-sabnzbd-extended) changes before building out a readarr-extended...

It is something I'm interested in doing... Just haven't gotten to investigate much, so if you know other CLI based tools that could be applicable, please feel free to link them here...

**Comment by steve1977** [comment]
Shall we move this somewhere else to continue the discussion.

I'd be interested to learn how you are dealing with audiobooks? Readarr doesn't feel perfect for it, so maybe you have other ideas? Ideally automated, ideally with metadata, ideally avoiding incompletes, ideally allowing different languages.

The linked scripts above read very powerful as they convert and allow Plex-support. But not fully clear to me how they all link together and what it takes to turn this into some audiobook magic...

Any pointers or experience sharing appreciated.

**Comment by RandomNinjaAtk** [comment]
Readarr-extended may come in the future, but a script was just added to sabnzbd-extended to help with readarr and audiobooks: https://github.com/RandomNinjaAtk/docker-sabnzbd-extended/commit/e4d78864a6f20dc37449300a672020d1243987ca

**Comment by RandomNinjaAtk** [comment]
WIP, no ETA... https://github.com/RandomNinjaAtk/docker-readarr-extended

**Comment by steve1977** [comment]
An "audio-book Readarr" is what has been asked for many times, so this has the potential to turn into this. So, people could run readarr for ebooks and readarr-extended for audiobooks.

Are you considering to integrate beets-audible to sabnzbd-extended or would this be better covered by readarr?
