### ISSUE TITLE
Audio.sh marks albums with [silence] before bonus tracks as Not Found

### ISSUE THREAD

**Issue by racedale** [RandomNinjaAtk/docker-lidarr-extended#174]
**Describe the bug**
Albums with bonus tracks have extra `[silence]` tracks added on music brainz, but Deezer/Tidal exclude those tracks, since they aren't recordings to be listened to. The audio script was able to download all the "real" tracks successfully, but then marks the album as "not found". 

**To Reproduce**
1. Add Hanson - Anthem album
2. run Audio.sh
3. See log for `61.904761904761905% Tracks found`, marking album as not found

**Expected behavior**
Should be able to download album from Deezer/Tidal, possibly by filtering out "[silence]" tracks. Or at least logging out a message that states what/how to update MusicBrainz to be compatible (like with the Deezer/Tidal artist not found)

**Log Data**
https://pastebin.com/qkZJCqW7

**Docker Info:**
 - Docker Version: 20.10.3
 - Extended Script Version: 1.0.306

**Additional context**
https://musicbrainz.org/doc/Style/Unknown_and_untitled/Special_purpose_track_title
MusicBrainz (21 tracks - 13-20 are `[silence]`): https://musicbrainz.org/release/5733bb6e-4d3e-4dba-845b-d272ed6da595
Deezer (13 tracks): https://www.deezer.com/us/album/170793392
Tidal (13 tracks): https://listen.tidal.com/album/68739664

**Comment by RandomNinjaAtk** [comment]
So you need to add a release that matches the release on service. Lidarr will never match an album that doesn't have the same number of tracks. So to resolve this, I suggest you add a 13 track release to the release group on musicbrainz.

Making changes to the script won't solve the root problem and likely won't work based on what I said above. 

For a recommended way to add a release to musicbrainz, see here: https://github.com/RandomNinjaAtk/docker-lidarr-extended/wiki/Extended-Audio-Script-Information#q-i-see-my-missing-music-in-deezer-but-it-seems-complicated-to-add-it-to-musicbrainz-any-suggestions

**Comment by RandomNinjaAtk** [comment]
@racedale Just fyi, it looks like you may have added the release, but it is set as unknown. Lidarr will not pull in Unknown releases. So you should update that. If you have more questions about it, ask the Lidarr support team.
