### ISSUE TITLE
Possible to set country for Deezer?

### ISSUE THREAD

**Issue by stayupthetree** [RandomNinjaAtk/docker-lidarr-extended#176]
On my home server I got this setup perfectly. I am setting it up on my remote server which is located overseas. It appears Deezer uses geolocation as all of the top artists it adds are European in origin. 

Can Deezer be set to US?

Wanted to ask in the Discord but can't seem to locate it.

**Comment by RandomNinjaAtk** [comment]
Don't think it's possible to set the region, that would be a deemix  issue.

**Comment by stayupthetree** [comment]
Can close this. I totally forgot about deemix not being you. From what I can tell for free users it is based on your IP location, so VPN would change it. If you are a paid deezer user it will base it on what country your payment is from.

**Comment by Yosh82** [comment]
There is an option for Deezer recommendations per country setting from what I can see, but unsure how it would integrate with LE. I've noticed my recommendations / top artists seem a bit random and unsure how it determines it by default, so if this is something that could be implemented as a variable in the docker, it would be a nice one to have.

[https://support.deezer.com/hc/en-gb/articles/360012847878-Changing-your-country-recommendations-on-Deezer](url)

**Comment by RandomNinjaAtk** [comment]
@Yosh82 Everything relies on Deemix, if deemix CLI cannot be configured to select a particular region, that isn't possible... 

Additionally, I'm not sure Deezer API supports region selection/configuration

**Comment by Yosh82** [comment]
As always, thanks for the response. I'll have to buy you a few "cups of coffee" once I've caught up with my xmas expenses.... such a great project and support is awesome.

Happy new year all, have a good one!
