### ISSUE TITLE
[Bug]: Related artist failing to add, API error.

### ISSUE THREAD

**Issue by richardap1** [RandomNinjaAtk/docker-lidarr-extended#179]
Enabling the related artist feature causes errors in API call

All I did was enable the feature in my compose file.

[Error] Lidarr.Api.V1.Artist.ArtistController.AddArtist (Lidarr.Api.V1): {
  "$": {
    "errors": [
      {
        "errorMessage": "\u00272\u0027 is invalid after a value. Expected either \u0027,\u0027, \u0027}\u0027, or \u0027]\u0027. Path: $ | LineNumber: 4 | BytePositionInLine: 0."
      }
    ],
    "validationState": "invalid",
    "isContainerNode": false
  }

**Comment by RandomNinjaAtk** [comment]
Do you have multiple root folders in Lidarr? That is likely the issue.

This does not support multiple root folders...

**Comment by richardap1** [comment]
Yes, two root folders.  

Ok, no worries. Thanks.
