### ISSUE TITLE
[Feat]:  Video Downloader needs Artist Disambiguation

### ISSUE THREAD

**Issue by JacquelineHyde** [RandomNinjaAtk/docker-lidarr-extended#180]
**Is your feature request related to a problem? Please describe.**
My artists have the disambiguation in the folder name so they're detected correctly in Plex. The video downloader defaults to non-disambiguated.

**Describe the solution you'd like**
Go by the Artist folder name in Lidarr so it matches.
Or at least give the option in a config file

**Describe alternatives you've considered**
Manually adding the disambiguation after the video downloads.

**Additional context**

**Comment by RandomNinjaAtk** [comment]
Plex won't detect them correctly with folder/artist disambiguation, that is why it was intentionally left out...
