### ISSUE TITLE
[Bug]: Tidal-DL keeps requesting auth when full bandwidth is available 

### ISSUE THREAD

**Issue by Yosh82** [RandomNinjaAtk/docker-lidarr-extended#182]
**Describe the bug**
Tidal auth keeps requesting auth, within the last 2 hours, I've had to re-auth at least 6 times, it then downloads, but not long after, requires another auth. This has been an ongoing issue for around a month, but I've just kept re-authing. As it continuously happens, I thought I'd raise a bug report.

**To Reproduce**
Steps to reproduce the behaviour:
1. Auth with tidal via url
2. Works briefly (varies on time, sometime for 5mins, other times a bit longer) before asking for re-auth

**Expected behaviour**
Keep the auth for the 7 days as the script states the token is valid for this amount of time

**Log Data**
I can provide log file if required

**Docker Info:**
 - Unraid docker, 20.10.21
 - Extended Script Version - current

**Additional context**
This seems to be related to the speed it downloads at. For example, if I set my SABnzbd to 4MB download speed (my max DL speed is only 6MB), and something is downloading, Tidal doesn't seem to drop the auth. Once the full bandwidth is available, this seems to cause the issue. A potential solution from what I've experienced would be to be able to set a download speed limit for the script?

I've tried re-authing via the console, scripts, /scripts/tidal-dl.json - but doesn't resolve it. 

Update: Since posting this when this dropped auth around 20mins ago, it has lost auth again. It states 6days 23hours "good" for the access token, but is asking to auth again.

![image](https://user-images.githubusercontent.com/106485860/211907400-b70d4c91-827d-4371-b3d4-d4f9c102bc00.png)

**Comment by Yosh82** [comment]
A bit more context, I've just re-authd again at 20:18:32 - I'll update again once it asks for auth again.

![image](https://user-images.githubusercontent.com/106485860/211909613-d1003e68-7664-4ec9-8f72-1e88370aea94.png)

Thanks in advance for your support

**Comment by RandomNinjaAtk** [comment]
Basically the script makes a maximum of 6 attempted downloads per client. If the client fails to download anything for all 6 attempts, you get this error and that causes the script to notify you to re-authenticate.

So your issue is likely caused by content just not being available... based on some of the messages in your log file... The only way I could think you could resolve it is to unmonitor those particular albums...

Relevant lines of code:
https://github.com/RandomNinjaAtk/docker-lidarr-extended/blob/00421aa29739d0c3469bdbf66c274914efa4263a/root/scripts/Audio.sh#L422-L491

**Comment by Yosh82** [comment]
That adds up, a lot of searches do come back as failed / cannot find, as my library is huge and admittedly, now messy due to adding so many related artists. It obviously takes longer to search when the bandwidth is in use, so all makes sense now. 

Thanks for looking into this, time to start a bit of house-keeping on Lidarr.
