### ISSUE TITLE
[Feat]: Flac to aac vbr 3

### ISSUE THREAD

**Issue by dvdgorila** [RandomNinjaAtk/docker-lidarr-extended#185]
Hello RandomNinjaAtk,

Is it possible to grab flacs, encode to AAC VBR 3 and keep the flac files as an archive? 

I saw the option to change the bitrate but didn't see an example or how  I could set the vbr to  vbr=3 in the unraid parameters. 

Thanks, 
Dvdgorila

**Comment by RandomNinjaAtk** [comment]
No, it will not keep 2 copies, it will convert to AAC and a preferred nitrate (not vbr).

It would be simpler to have 2 lidarr setups, one for flac and one for aac...

**Comment by RandomNinjaAtk** [comment]
2 Installations, targeting both desired qualities would be the best way forward. You can use lidarr's list sync feature to sync the artists between both installations.
