### ISSUE TITLE
[Bug]: can't hit api at http://lidarrIP:8686/api?apikey=XXXX

### ISSUE THREAD

**Issue by captainnapalm** [RandomNinjaAtk/docker-lidarr-extended#188]
**Describe the bug**
Attempting to hit the api to confirm version at http://lidarrIP:8686/api?apikey=XXXX returns a 404 instead of the expected json output of something like: 
```
{
    "current": "v1",
    "deprecated": []
}
```

I attempted to use the lidarr.audio v1.0 api docs page to test (https://lidarr.audio/docs/api/#/), but received a `TyperError: NetworkError when attempting to fetch resource.` I am however able to receive an output for something like http://lidarrIP:8686/api/v1/system/status?apikey=XXXX (https://lidarr.audio/docs/api/#/System/get_api_v1_system_status).

This was all brought on by attempting to run [lidarr-true-singles](https://github.com/chxseh/lidarr-true-singles) and the api check failing.

**To Reproduce**
1. Navigate in browser to http://lidarrIP:8686/api?apikey=XXXX
2. Receive lidarr's 404 page

**Expected behavior**
Expected output is json as formatted above

**Log Data**
[Imgur](https://imgur.com/iNevJEF) 

**Docker Info:**
 - Docker Version: 1.1.1.2762-ls68 by linuxserver.io
 - Extended Script Version: not sure

**Comment by RandomNinjaAtk** [comment]
Seems like your having a general lidarr issue, I only support the packaged scripts. The scripts do everything via API calls, so the API is definitely functioning as expected.

Lidarr API examples from script:
https://github.com/RandomNinjaAtk/docker-lidarr-extended/blob/00421aa29739d0c3469bdbf66c274914efa4263a/root/scripts/Audio.sh#L783

https://github.com/RandomNinjaAtk/docker-lidarr-extended/blob/00421aa29739d0c3469bdbf66c274914efa4263a/root/scripts/Audio.sh#L55

https://github.com/RandomNinjaAtk/docker-lidarr-extended/blob/00421aa29739d0c3469bdbf66c274914efa4263a/root/scripts/Audio.sh#L965


You may want to ask the author of the other docker for help...
