### ISSUE TITLE
[Feat]: Create Tidal and Deezer as indexers/downloaders

### ISSUE THREAD

**Issue by captainnapalm** [RandomNinjaAtk/docker-lidarr-extended#189]
**Is your feature request related to a problem? Please describe.**
To avoid seeing constant error/warning messages in lidarr (I don't use any other indexer/downloaders other than Tidal/Deezer with my instance) it would be nice to have these created as indexers/downloaders within lidarr, similar to how [lidarr-on-steroids](https://github.com/youegraillot/lidarr-on-steroids) does.

**Describe the solution you'd like**
Create indexer/downloaders for the tidal and deezer extended scripts.

**Describe alternatives you've considered**
Considered using lidarr-on-steroids for deezer integration, and only use lidarr-extended for tidal, but this doesn't resolve the error/warning messages in lidarr-extended

**Comment by RandomNinjaAtk** [comment]
Out of scope for this project and not my skillset. What your asking for would not only require indexers, but compatible download clients, which deemix is sorta supported, but other clients would not work.

**Comment by RandomNinjaAtk** [comment]
change closed type
