### ISSUE TITLE
[Feat]: New Indexer (?)

### ISSUE THREAD

**Issue by Breakingx** [RandomNinjaAtk/docker-lidarr-extended#190]
**Is your feature request related to a problem? Please describe.**
Musicbrainz as Indexer is so slow with updating the song/album list that it is really nervwrecking.

**Describe the solution you'd like**
Is it possible to use for example Deemix as Indexer?

**Comment by RandomNinjaAtk** [comment]
No... Lidarr only uses musicbrainz database for sourcing album/artist information.... That would require a change in upstream lidarr, and I know for a fact that is not going to happen....

Musicbrainz is also community maintained, so be good community member and help maintain it by updating it if something is missing....
