### ISSUE TITLE
[Feat]: grabbing lyric files using tidal-dl

### ISSUE THREAD

**Issue by TheMinecraftGuyGuru** [RandomNinjaAtk/docker-lidarr-extended#192]
**Is your feature request related to a problem? Please describe.**
I stumbled upon Lidarr Extended when I was trying to figure out how to get Lidarr and Tidal-dl to play nicely together, I really like this project, however, I want to be able to grab the synced lyric files from Tidal as well.

**Describe the solution you'd like**
I see that in the recommended setup of Lidarr, you already have it set to copy over .lrc files, so the fix should be as easy as enabling .lrc file downloads in tidal-dl

**Describe alternatives you've considered**
simply running tidal-dl separately for each artist, which is super duper slow compared to the automated-ness of this.

**Comment by RandomNinjaAtk** [comment]
Lyric files should already work, you have to make sure they lidarr post processing scripts are enabled though. (Under connections)

**Comment by RandomNinjaAtk** [comment]
No response, lryic files should be grabbed when configured correctly.
