### ISSUE TITLE
Metadata profile when adding artists from Deezer artist/albumartist

### ISSUE THREAD

**Issue by steve1977** [RandomNinjaAtk/docker-lidarr-extended#199]
Not sure how LE determines what metadata profile is used. Can this be make optional and/or explain the logic that I can adjust for it? Thanks!

**Comment by RandomNinjaAtk** [comment]
LE doesn't care what profile, it only looks at the wanted/cutoff list.... So its whatever you configured your artists for...

**Comment by steve1977** [comment]
I am referring to when you use the setting to "import deezer artist". I have 4 metadata profiles. It picks one of them, but not clear why it chose that one.

**Comment by RandomNinjaAtk** [comment]
It probably uses the Any profile, the first one in the profile list... There isn't a way to specify and it uses whatever the default is, which you cannot choose which one is the default....

See here: 
https://github.com/RandomNinjaAtk/docker-lidarr-extended/blob/3f8436185bc6690c36ca7be712aa640c024348b8/root/scripts/AutoArtistAdder.bash#L135-L136
