### ISSUE TITLE
Deezer explicit or non feature request

### ISSUE THREAD

**Issue by Glynax** [RandomNinjaAtk/docker-lidarr-extended#2]
I'd still like the ability to choose if it searches/downloads non explicit tracks as I believe it still is grabbing the first result which seems to sometimes be explicit, sometimes isn't. Just trying to get my library to be consistent.

**Comment by Glynax** [comment]
Honestly I'd take anything that let's me prefer clean only, even if it greatly reduces the options. I realize I'm rather in the minority with that but I've never found another option to automate such a thing. If possible I'd like it to have a flag to prefer one or the other but also fall back to whatever available for completeness' sake.

**Comment by RandomNinjaAtk** [comment]
Should be added in latest update, please verify
