### ISSUE TITLE
[Bug]: /music appears to be mandatory

### ISSUE THREAD

**Issue by telix5000** [RandomNinjaAtk/docker-lidarr-extended#202]
I was consolidating my music libraries and removed /music from my docker compose. Upon spinning up my instance, I noticed /music was back; and after wiping it out and rebuilding it again, /music keeps coming back (to  some default where no data is) -- but the documentation doesn't list it has a mandatory mount. I could very well move things back and map things accordingly, but I wanted to know if this is actually mandatory, a bug, or if it was some oversight as the mandatory /'s are all fairly well spelled out on the main page. Thanks.

**Comment by RandomNinjaAtk** [comment]
How is it showing up? Is it showing up in Lidarr as a root folder?

**Comment by telix5000** [comment]
In Portainer I get this:

96bac9177337c27e58d8ce2430540ed93cc54c11acc26b494552afd34dae634d | /music

/music is not being used in the compose section, so it assigns this arbitrary mount to: /volume1/@docker/volumes/96bac9177337c27e58d8ce2430540ed93cc54c11acc26b494552afd34dae634d/_data

And in the Lidarr Status, you get /music; but obviously there isn't anything there.

**Comment by RandomNinjaAtk** [comment]
Latest changes should resolve it.... Keep in mind its untested because I do not have a similar environment to test with...
