### ISSUE TITLE
Bypass Tidal for music videos, use only YouTube

### ISSUE THREAD

**Issue by mrlespaulman** [RandomNinjaAtk/docker-lidarr-extended#209]
**Describe the bug**
I do not currently have a tidal account, and use lidarr-extended to scrape music videos from youtube. However, when the script finds a tidal link for a video in musicbrainz, it will prompt for tidal auth in the output logs, and will eventually quit the script. Then on script autorun, it will repeat the same process. The script is effectively stuck at the artist that has the tidal link. For what it's worth, there is a youtube link on the musicbrainz page as well, but the script seems to prefer the tidal link.

**To Reproduce**
1) Don't have a tidal account
2) Attempt to scrape music videos from an artist that has a tidal link in the musicbrainz listing

**Expected behavior**
I would like to find a way to disable tidal link scraping, since I do not plan on subscribing to tidal.

**Log Data**
```
`Starting login process...
Go to http://link.tidal.com/UWJHT within the next 5 minutes to complete setup.
Waiting for authorization...
[ERR] Login failed.Error while checking for authorization. Trying again...
[INFO] Download path:/downloads-lidarr-extended/videos/incomplete
[ERR] No result. [166356219]
Starting login process...
Go to http://link.tidal.com/FCGEN within the next 5 minutes to complete setup.
Waiting for authorization...
[ERR] Login failed.Error while checking for authorization. Trying again...
[INFO] Download path:/downloads-lidarr-extended/videos/incomplete
[ERR] No result. [166356219]
2023-03-05 15:39:17 :: Video :: 1.0.063 :: TIDAL :: ERROR :: Download failed
2023-03-05 15:39:17 :: Video :: 1.0.063 :: TIDAL :: ERROR :: You will need to re-authenticate on next script run...
2023-03-05 15:39:17 :: Video :: 1.0.063 :: TIDAL :: ERROR :: Exiting...

```
`

**Comment by RandomNinjaAtk** [comment]
Post your docker parameters, seems like a misconfiguration

**Comment by mrlespaulman** [comment]
here are the parameters i used when creating the docker container:
` docker create   
--name=lidarr-extended   
-v /var/lib/Lidarr:/config  
 -v /mnt/mediadownloads/Downloads:/downloads-lidarr-extended  
 -v /mnt/mediadownloads/music:/music 
  -v /mnt/mediadownloads/Concerts:/music-videos  
 -p 8686:8686  
 -e TZ=America/New_York   
-e PUID=1000  
 -e PGID=1000   
-e enableAudioScript=true  
 -e enableVideoScript=true  
 -e scriptInterval=15m  
 -e configureLidarrWithOptimalSettings=true  
 -e searchSort=date  
 -e audioFormat=native 
  -e audioBitrate=lossless  
 -e requireQuality=true   
-e enableReplaygainTags=true  
 -e audioLyricType=both 
  -e dlClientSource=both  
 -e arlToken=Token_Goes_Here 
  -e tidalCountryCode=US 
  -e addDeezerTopArtists=true 
  -e addDeezerTopAlbumArtists=true  
 -e addDeezerTopTrackArtists=true  
 -e topLimit=10  
 -e addRelatedArtists=false   
-e numberOfRelatedArtistsToAddPerArtist=5  
 -e lidarrSearchForMissing=true   
-e addFeaturedVideoArtists=false 
  -e plexUrl=http://x.x.x.x:32400  
 -e plexToken=Token_Goes_Here  
 -e youtubeSubtitleLanguage=en  
 -e enableQueueCleaner=true  
 -e matchDistance=5  
 -e enableBeetsTagging=true  
 -e beetsMatchPercentage=90   
-e retryNotFound=90  
 --restart unless-stopped  
 randomninjaatk/lidarr-extended:latest
`

guessing it has something to do with the client source variable?

**Comment by RandomNinjaAtk** [comment]
Correct, you need to set it to deezer, so tidal is skipped...

**Comment by RandomNinjaAtk** [comment]
Should be resolved with config change...
