### ISSUE TITLE
[Feat]: Rescan artist for music videos after updating MusicBrainz links

### ISSUE THREAD

**Issue by mrlespaulman** [RandomNinjaAtk/docker-lidarr-extended#210]
First of all, this project is incredible. Thank you for your work!

 Is there currently a way to rescan an artist for music videos after adding new links to MusicBrainz? Currently when the script scans artists again after adding links to MusicBrainz, it says:

`2023-03-09 21:16:17 :: Video :: 1.0.063 :: 12 of 240 :: Alina Baraz :: Music Videos previously downloaded, skipping... `

**Comment by RandomNinjaAtk** [comment]
Update to the latest version

**Comment by mrlespaulman** [comment]
Awesome! Can confirm this now works with the latest docker image.
