### ISSUE TITLE
[Bug]: Files Not Automatically Importing for Missing Release Group

### ISSUE THREAD

**Issue by jessetn** [RandomNinjaAtk/docker-lidarr-extended#212]
I'm having to manually import media that should otherwise have all necessary matching information for an automatic import with no errors, except for a missing "Release Group". I doesn't appear to have a switch in the settings for this requirement. I've noticed this for the past few releases but am now constantly having to manually import. Is this a bug or expected behavior?
![image](https://user-images.githubusercontent.com/19999918/224813910-5d0b2a64-a6a5-43d0-ae3a-90bdb9f5e4b0.png)
Version
1.1.3.2982
Package Version
1.1.3.2982-ls77 by [linuxserver.io](https://www.linuxserver.io/)
.NET
Yes (6.0.7)
Docker
Yes
DB Migration
63
Database
Sqlite 3.40.1
AppData directory
/config
Startup directory
/app/lidarr/bin
Mode
Console

**Comment by RandomNinjaAtk** [comment]
Imports are handled by Lidarr, this is not a bug with lidarr-extended but an issue with how upstream lidarr imports/matches releases. You can reach-out to Lidarr support channels for more information/support but there isn't anything I can do about it here....

**Comment by RandomNinjaAtk** [comment]
On that note, if you can identify its a problem with one of the included scripts, I'll gladly investigate further. But this does not appear to be an issue with that....

**Comment by jessetn** [comment]
There a [Reddit post](https://www.reddit.com/r/Lidarr/comments/11lb0fi/what_is_release_group/) from Lidarr's support from January saying Lidarr does not require Release Group on import. I swear I also ran across the same statement on their Github but can't find atm. If I do I'll post

**Comment by cbeauhilton** [comment]
@RandomNinjaAtk I'm not @jessetn but having the same issue, and yes, the files are imported from the usual methods.
