### ISSUE TITLE
[Feat]: Audio script to scrape the tracks within albums missing and try to download singles from deezer. 

### ISSUE THREAD

**Issue by djcath** [RandomNinjaAtk/docker-lidarr-extended#216]
**Is your feature request related to a problem? Please describe.**
It would be helpful to scrape deezer for missing tracks from albums individually for when the album itself is not available. 

**Describe the solution you'd like**
for the script to check the track names within the album with the artists name to see if the song is available for download individually.
This would also help for scraping “singles” instead of Albums.

**Comment by RandomNinjaAtk** [comment]
Lidarr is an album manager, not singles manager. Lidarr will not import single track files, only complete albums.
