### ISSUE TITLE
Files are randomly unmapped and remapped

### ISSUE THREAD

**Issue by mrlespaulman** [RandomNinjaAtk/docker-lidarr-extended#218]
**Describe the bug**
Files are randomly unmapped and remapped to songs. This happens for all artist and albums marked "Monitored" in Lidarr-extended. As the songs are unmapped, a "?" shows in the status column in the song listing, which upon hovering with mouse says "TBA". I can confirm that the files themselves are not moving or deleting. The files will randomly remap again to the song files. I have also noticed the the "Rescan Folders" task is almost always running, and lasts days at a time. I have tried removing my root folder within Lidarr and re-adding it, and the same issue occurs. I can import the missing songs via "Manual Import" on the artist page, but the same issue inevitably happens after import. 

This does not affect access or playing of the files through Infuse/Jellyfin/Plex. They all show up as normal. 

**To Reproduce**
Open Lidarr
Click on an artist/album
Some songs will have "?" in status column
Refresh after 5m
More/less songs will have "?" in status column

**Expected behavior**
I expect the files to stay mapped to songs, as the location of them is not changing on the drive.

**Log Data**
![Screenshot 2023-03-24 121217](https://user-images.githubusercontent.com/127054306/227582783-a7eda3d0-0241-4000-b810-e3b6a5912805.png)
![Screenshot 2023-03-24 121305](https://user-images.githubusercontent.com/127054306/227582789-9295fd45-e12a-4f6b-b23d-00134503e59d.png)
![Screenshot 2023-03-24 121526](https://user-images.githubusercontent.com/127054306/227582793-2eac2c09-5f73-4861-81a5-90280d7ae6a4.png)
![Screenshot 2023-03-24 121547](https://user-images.githubusercontent.com/127054306/227582795-6db6fabe-7550-471f-93ae-7ad59276d6e7.png)

**Comment by RandomNinjaAtk** [comment]
Sounds like an upstream lidarr issue. You should report it there...

**Comment by mrlespaulman** [comment]
Ok, I'll bring it up over there. One consequence is that the audio script is continually downloading tracks that Lidarr is erroneously reporting as missing, then on import is overwriting the existing file with the new download. Doesn't really affect the end user experience, but it results in the script wasting a lot of time redownloading tracks unnecessarily.
