### ISSUE TITLE
Tidal-dl downloading as root:root

### ISSUE THREAD

**Issue by shyshapestory** [RandomNinjaAtk/docker-lidarr-extended#219]
This is kinda piggybacking this one:
https://github.com/RandomNinjaAtk/docker-lidarr-extended/issues/217

When an album is moved into complete, it's chmod'ed correctly, but due to being owned by root:root, Lidarr cannot import it. I did set up the container with correct PUID and PGID.

I tried changing it manually to perform chown after chmod, and it worked, but as the script was updated when I restarted the container, the edit disappeared.

**Comment by RandomNinjaAtk** [comment]
Even if owned by root, you likely have some other issue because there would be a lot more reports if there was an actual issue. The permissions are set to be pretty lenient as 666 or 777. So your failure to import is not a permissions issue or ownership issue.
