### ISSUE TITLE
[Feat]: Gather all artist song

### ISSUE THREAD

**Issue by thomas-massey** [RandomNinjaAtk/docker-lidarr-extended#221]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I add an artist and only manage to get half of their songs as they arent properly indexed on Musicbrainz when there are clearly many more songs on their profile like on Tidal and Deezer.

**Describe the solution you'd like**
Some sort of implementation, (having it in the webUI would be very efficent but quite a pain) so maybe just an ENV variable like "ForceDownloadArtist" where by default it is off, but if true, upon adding/searching for a track/artists you instead of downloading the song, download everything.

**Describe alternatives you've considered**
WebUI is efficent but difficult and ENV is simple and not as hard to debug.

**Additional context**
I myself us Tidal so the Tidal-DL supports download via artist ID/URL so this is where it would need to be implimented:

https://github.com/RandomNinjaAtk/docker-lidarr-extended/blob/15ae5634c83006aedfa62a0f2b68160b2543bbba/root/scripts/Audio.sh#L1359

```msuicbrainzTidalDownloadAlbumID``` (also is that a typo?), could be ```msuicbrainzTidalDownloadArtistID```

https://github.com/RandomNinjaAtk/docker-lidarr-extended/blob/15ae5634c83006aedfa62a0f2b68160b2543bbba/root/scripts/Audio.sh#L334-L341

https://github.com/RandomNinjaAtk/docker-lidarr-extended/blob/15ae5634c83006aedfa62a0f2b68160b2543bbba/root/scripts/Audio.sh#L464-L467

Sorry if the code I have refrenced is wrong - my bash is a little rusty!

Beautifuly program - thank you for the creation!

**Comment by RandomNinjaAtk** [comment]
I had previous projects that operated similar manor to what your suggesting, but that is not the goal here. 

Improving musicbrainz is the best way forward because it's not a workaround and it helps the entire community. You can feel free to look through my older repos, but I will not be working on this..
