### ISSUE TITLE
lidarr-extended "duplicating" artist folders

### ISSUE THREAD

**Issue by woonaval** [RandomNinjaAtk/docker-lidarr-extended#229]
Hello, 
I am running lidarr-extended on my existing music library, and in general it works fine. There is an issue I would like to comment. Lidarr is downloading missing albums from existing artists in my library, that's perfect. But the artist folder is wrong, lidarr is creating a new folder with a somewhat extended description of the artist, instead of just the artist name. Example:

- Disturbed
- Disturbed (USA metal band)

Because of this, I'm getting 2 folders for the same artist (tags in the audio files are all good with just the artist name). 
You can see the behaviour [here](https://i.imgur.com/OmhNbqa.png)
For me it's fine keeping the longer/descriptive artist name, but I would like to have just one folder per artist. Do you know how can I fix this? I fear that if I move the new albums to the "old" folders, lidarr will try to re-download the albums.
Thank you!

**Comment by Yosh82** [comment]
As lidarr can only have one directory per artist, it has put the new files in the new path. As you have already started downloading using the new file naming script, the easiest option I can think of is to set lidarr to rename the files back to your original file naming, that will merge the folders back to just "Eminem" for example.

Then, once all are merged, do another mass-edit, using the rename function, to the new naming structure.

![image](https://user-images.githubusercontent.com/106485860/235133864-5a23a48c-5bfd-4826-a4e5-04e78798c4d7.png)

Hope that makes sense.

**Comment by RandomNinjaAtk** [comment]
As the other user said, files are managed by your lidarr settings, so you need to adjust and move accordingly.

**Comment by woonaval** [comment]
ok, I found under Advanced Settings in Media Management, that by default "Artist Folder Format" was set to "{Artist CleanName}{ (Artist Disambiguation)}". I removed the Artist Disambiguation part and probably this will solve my issue. Thanks!
