### ISSUE TITLE
[Bug]: Tidal Artist Link not found despite being added to musicbrainz

### ISSUE THREAD

**Issue by GinjuGG** [RandomNinjaAtk/docker-lidarr-extended#255]
**Describe the bug**
Audioscript cant find Tidal Link from musicbrainz, but the Tidal Artist Link is linked in Musicbrainz.

**To Reproduce**
1. Use Audioscript
2. Configure Tidal
3. Let Tidal Download Artists
4. see lidarr.link/logfile/tidal-artist-id-not-found.txt

**Expected behavior**
Audioscript should find the Tidal Artist Link from musicbrainz.

**Log Data**
![grafik](https://github.com/RandomNinjaAtk/docker-lidarr-extended/assets/5270413/bf66aeb8-50c3-46a2-8fbd-b4801ca3e008)

Example: 
https://musicbrainz.org/artist/886dc0c9-3351-4d2d-b762-060cf1e66929/edit
https://tidal.com/browse/artist/10789784

**Docker Info:**
newest version (lidarr, docker and audioscript)

**Comment by RandomNinjaAtk** [comment]
Your local lidarr instance has to have the URL. Due to API constraints the script no longer checks musicbrainz directly. So  you can try refreshing the artist data in Lidarr to see if you get the URL.
