### ISSUE TITLE
[Bug]: Video script isn't moving beyond "IMVDB Slug Not Found"

### ISSUE THREAD

**Issue by Hendo16** [RandomNinjaAtk/docker-lidarr-extended#257]
After spending some time adding music video entries into MusicBrainz for Knocked Loose, I tried adding them to lidarr however when the video script runs, it runs through all of my artists and either returns "Chache is already up-to-date, skipping..." followed by "Music Videos previously downloaded, skipping..." or "IMVDB Slug Not Found..."

Knocked Loose is the last on the list, but it doesn't seem to move onto MusicBrainz to attempt to get the slug or progress any futher. I also can't find an entry for Knocked Loose in '\extended\logs\video\imvdb-link-missing'. Other artists are in there that seemed to have downloaded videos fine when I used this application last (which was a number of months ago, I am just getting back into it) so I feel like somethings gone wrong. I tried setting my logging level to debug, but I can't seem to get any further than

`2023-06-19 21:07:13 :: Video :: 1.0.8 :: 30 of 30 :: Knocked Loose :: Checking for IMVDB Slug`
`2023-06-19 21:07:13 :: Video :: 1.0.8 :: 30 of 30 :: Knocked Loose :: IMVDB Slug Not Found...`

And then nothing until it restarts again in 15 minutes.

The most frustrating thing (out of your purview) is the fact that Knocked Loose aren't on IMVDB, and there's no way to gain access to add them to that site which would probably solve this specific issue but again, I have used this to get videos from other artists that aren't on IMVDB before so it should still be working.

**Comment by RandomNinjaAtk** [comment]
Due to api restrictions and receiving complaints/threats, all direct musicbrainz functionality was removed. The only method to get videos is from IMVDB unfortunately.

So your not experiencing a bug, it's a loss of functionality and there isn't anything that can be done about it.

**Comment by Hendo16** [comment]
Aw damn! That sucks - are you aware of any ways to actually add items to IMVDB or can it only access what's currently listed?

**Comment by RandomNinjaAtk** [comment]
I tried to add a video a while ago, but it appears the site isn't being actively maintained and my addition is stuck waiting for approval. Recent content seems to get added, but I don't think there is any hope of user additions.
