### ISSUE TITLE
Related artist improvements

### ISSUE THREAD

**Issue by Truxnell** [RandomNinjaAtk/docker-lidarr-extended#3]
Just a few notes on your related artists new feature.  Ive taken a local coy and made a few tweaks:

* It parses all artists, both monitored and unmonitored.  This might not be the best behavior, so i modified mine to remove unmonitoried.
( I have added `| jq -r 'walk(if type == "object" and (.monitored == false) then empty else . end)'` to my dev copy)
* It automatically kicks off a lidarr search, which depending on setup may trigger searches on other existing tools - i prefer not to search elsewhere until the included downloaders are searched.
( I have added `\"addOptions\":{\"searchForNewAlbum\":false}` to my modified script in the data field that is passed to Lidarr)

**Comment by Truxnell** [comment]
Ill have a look on the weekend.

I might not quite get your vision for the tool, but I'm thinking on the second point (search for new albums) this might be something you would prefer exposed via ENV for users to choose either way?

Forgot to mention: Thanks for the script!

**Comment by RandomNinjaAtk** [comment]
After the latest image builds, you should try it. I included the enhancement, but probably went about it a bit differently.

**Comment by Truxnell** [comment]
Awesome, ta!
