### ISSUE TITLE
Upgrade from MP3 to FLAC via script

### ISSUE THREAD

**Issue by tape-guy** [RandomNinjaAtk/docker-lidarr-extended#4]
I know you can set this up in quality profile options to upgrade files, is it possible to trigger in the script? AMD was awesome, really like this build so thank you for your time!

**Comment by RandomNinjaAtk** [comment]
I think with the latest changes, upgrades should be possible, give it a try and report back....

**Comment by tape-guy** [comment]
Starting now, will report back soon, thank you again!

**Comment by RandomNinjaAtk** [comment]
Yeah, lidarr handles all data movement, so if there is an issue with that, you'd need to report it there.

**Comment by tape-guy** [comment]
Can confirm it is working, excellent work!

**Comment by CaptainJawZ** [comment]
Excuse the super noob question I've been trying to figure out how, but how do I go about doing this? is it automatic, as in setting up the profile to lossless (with upgrades allowed) and the lossless variable set on docker-compose?

**Comment by RandomNinjaAtk** [comment]
Yeah, basically. You've got the right idea.
