### ISSUE TITLE
[Feat]: save the music video next to the matching track

### ISSUE THREAD

**Issue by ecarlson94** [RandomNinjaAtk/docker-lidarr-extended#58]
**Is your feature request related to a problem? Please describe.**
Plex can automatically associate music videos with their track. However, the video needs to be placed next to the track file with the exact same name. Here is a tip from their [support page](https://support.plex.tv/articles/205568377-adding-local-artist-and-music-videos/) in this topic:

> Tip!: To have the music video associated with the track, it must start with the exact filename of the corresponding music track and must be in the same directory as that track.

**Describe the solution you'd like**
I would like the new video to be placed in the album folder with it's associated track and named the same as the track. Or maybe `<track file name> - Video.<extension>`. Then, if a match is not found, place the video at the root of the artist folder.

As an added bonus, it would be nice if the script would periodically check to see if the tracks for unmatched videos have been downloaded and then move the newly matched videos.

**Describe alternatives you've considered**
Manually moving/renaming the music video files. But then, that defeats the point of automation software. 🤣 

**Additional context**

**Comment by RandomNinjaAtk** [comment]
The point of the existing script is to drive for maximum compatibility between multiple apps (kodi, jellyfin, emby, etc.), not just Plex. This feature is only supported by Plex and would likely result in the need to have multiple copies of the same video to fully support the feature, which is a lot of duplicate data and not ideal.
