### ISSUE TITLE
How do you see deemix/deezer activity? 

### ISSUE THREAD

**Issue by infinitenewworld** [RandomNinjaAtk/docker-lidarr-extended#67]
I don't see Deemix or Deezer anywhere? I've added my arl token but have no way to know if anything is being sourced through Deemix, is there a way to monitor this? Nothing is showing up in activity etc. 

Thanks!

**Comment by RandomNinjaAtk** [comment]
You need to check the logs, either watch the containers log or view the log files in lidarr

**Comment by RandomNinjaAtk** [comment]
Closing due to lack of response, my previous comment is the answer your looking for anyways...
