### ISSUE TITLE
[Feat]: Music Video Quality

### ISSUE THREAD

**Issue by senses3** [RandomNinjaAtk/docker-lidarr-extended#71]
**Is your feature request related to a problem? Please describe.**
AFAICT there is no option/env to specify minimum quality for downloaded music videos

**Describe the solution you'd like**
A config option to specify minimum music video quality

**Describe alternatives you've considered**
Looked through config, checked existing github issues.

**Additional context**
Would also be cool to see music video listed in lidarr under artist, but this is probably a separate issue.

**Comment by RandomNinjaAtk** [comment]
I think this is a neat idea to be considered, what would be the limiting factor?

Resolution? 

I would want to keep it as simple as possible to make it easier to implement and to understand.

**Comment by senses3** [comment]
Maybe make yt-dlp options available as envs so you could just set whatever download options you want to specify, whether it's video quality, file type, etc.

**Comment by RandomNinjaAtk** [comment]
Try setting a the "videoFormat" parameter with your desired setting...
