### ISSUE TITLE
[Feat]: Clarify where the plex token is found

### ISSUE THREAD

**Issue by ShivamAmin** [RandomNinjaAtk/docker-lidarr-extended#92]
**Is your feature request related to a problem? Please describe.**
Not a problem for some, but it does take some research to find out that it's not a plex claim token, but an authentication token. 

**Describe the solution you'd like**
Update the `-e plexToken=` function description with a link that points to https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/ which describes how to get the token for the plexToken parameter.

**Describe alternatives you've considered**

**Additional context**
Clarifying the readme will help users

**Comment by RandomNinjaAtk** [comment]
Done!
