### ISSUE TITLE
Wrong year id tagging on album after import, beet not working?

### ISSUE THREAD

**Issue by krokenn** [RandomNinjaAtk/docker-lidarr-extended#93]
hello,

when importing AC/DC High Voltage (original album & International version) 	Feb 16 1975 im getting folder %year% set to 2014 ( this updates and also ID tagging on tracks to 2014, it looks like data is from deezer but is not getting properly tagged with beet? i see replagain is doing its job in incomplete folder where and when is beet running?

using latest docker with original settings from script.

EDIT: now it updated to 1975 but the tracks are still 2014

**Comment by Yosh82** [comment]
Regarding the release year, I think the issue with the tagging is just the way it tags from musicbrainz by default, the same as Picard. On Picard, I have set a script to use the Original release year, not the re-release ones. Is this something that could be implemented for LE?

The Picard script which I use:
$set(date,$left(%originalyear%,4))

Thanks.

**Comment by krokenn** [comment]
ok so it did update album folder name to 2014 now but the tracks are still tagged 2014

**Comment by RandomNinjaAtk** [comment]
Tagging is handled by lidarr, so it has nothing to do with the scripts used in this case... Also beets was disabled, its technically still installed, but not used...

You should take your issue with Year tagging with Lidarr itself, because that handles the tagging.

**Comment by Yosh82** [comment]
> Tagging is handled by lidarr, so it has nothing to do with the scripts used in this case... Also beets was disabled, its technically still installed, but not used...
> 
> You should take your issue with Year tagging with Lidarr itself, because that handles the tagging.

Thanks. I assumed that would be the response but thought I'd ask as I saw another with the same issue. Lidarr (original) also did this, which is why I used picard in the end.
