### ISSUE TITLE
There is no information on how to setup tidal

### ISSUE THREAD

**Issue by cherryontopknife** [RandomNinjaAtk/docker-lidarr-extended#96]
We're told to check the output logging, but I don't see anything in the console that describes how to setup tidal with lidarr-extended.

Even simple steps on what to do would be much appreciated.

**Comment by RandomNinjaAtk** [comment]
There isn't really anything to setup. Basic instructions:

1. Restart/Start docker container
2. Watch Container console log
3. Authenticate when prompted

Basically the scripts with autostart enabled, will kick off after about 2-3min after the container is first started. And in the console output, you'll see a prompt to authenticate the tidal client.

**Comment by cherryontopknife** [comment]
Thanks for responding.

I have both the console open and the logs open. I start Lidarr, and after 2 minutes the scripting starts. My logs have information about Tidal, but I don't see anything about how to authenticate in either the console or the log.

![image](https://user-images.githubusercontent.com/109005960/196195172-d10201f5-d421-4144-aa31-3bc73dba61ba.png)

**Comment by RandomNinjaAtk** [comment]
Wait a bit longer, you will see it in the log output, its really all I can tell you, its not a perfect solution, but there is no other solution to improve it that I'm aware of.... If you use the webhook feature, you'll get a notification via the webhook when its required:
https://github.com/RandomNinjaAtk/docker-lidarr-extended#parameters

**Comment by RandomNinjaAtk** [comment]
Updated the readme, with a link to this issue describing the process for authing. I would recommend that you use the webhook, it makes it was simpler to track when it needs your attention.
