### ISSUE TITLE
[Bug]: Docker for Windows is crashing when trying to create a database based off my artist library (over 2000 artist)

### ISSUE THREAD

**Issue by Deathbot64** [RandomNinjaAtk/docker-lidarr-extended#97]
**Describe the bug**
Docker for Windows will crash when trying to build artist database
**To Reproduce**
1. Create new container
2. add root folder for music library
3. Let it scan
4. It will start importing artist
5. After a bit it will crash docker for windows and a docker or system restart is needed to get it to work again

**Expected behavior**
It should be able to create the database from my library without issues or crash

**Log Data**
None at this time

**Docker Info:**
 - Docker Version: Docker for Windows 4.12.0
 - Extended Script Version latest

**Additional context**
Was able to get it to work after multiple scans before on an older container but I had to re do it recently and have been have issues with the scan not even start for rescan folders.

**Comment by RandomNinjaAtk** [comment]
You should setup the Linuxserver.io Lidarr container (develop tag) to see if you have the same issue. This container is based on that and it sounds like your having a problem  with the base container, which is not something I can help you with here...

**Comment by RandomNinjaAtk** [comment]
Support here is only provided for the Scripts that are included, not for the base image container, docker, or lidarr. Since you seem to be having difficulty with those, you may need to request help elsewhere.
